
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasham
 */
public class StudentSeeResult extends javax.swing.JFrame {

    /**
     * Creates new form StudentSeeResult
     */
    public StudentSeeResult() {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldIDResult = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(204, 204, 255));
        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("See Student result");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 50));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 780, 420));

        jTextFieldIDResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldIDResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDResultActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIDResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 220, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 60, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("See Result");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 130, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Fade Black.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        jTextFieldIDResult.setText(jTable1.getModel().getValueAt(row, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentShown

    private void jTextFieldIDResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDResultActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //        String ID = jTextField16.getText();
        //        String S1 = jTextField15.getText();
        //        String S2 = jTextField5.getText();
        //        String S3 = jTextField7.getText();
        //        String S4 = jTextField8.getText();
        //        String S5 = jTextField9.getText();
        //        String S1M = jTextField10.getText();
        //        String S2M = jTextField11.getText();
        //        String S3M = jTextField12.getText();
        //        String S4M = jTextField13.getText();
        //        String S5M = jTextField14.getText();
        //
        //        DatabaseConnection db = new DatabaseConnection();
        //        db.AdminAddStudentResult1(ID, S1, S2, S3, S4, S5, S1M, S2M, S3M, S4M, S5M);
        //
        //        jTextField16.setText("");
        //        jTextField15.setText("");
        //        jTextField5.setText("");
        //        jTextField7.setText("");
        //        jTextField8.setText("");
        //        jTextField9.setText("");
        //        jTextField10.setText("");
        //        jTextField11.setText("");
        //        jTextField12.setText("");
        //        jTextField13.setText("");
        //        jTextField14.setText("");
        String ID = jTextFieldIDResult.getText();
       try
        {
            DatabaseConnection db =new DatabaseConnection();
            ResultSet rs = db.ps.executeQuery("select *from studentdetails where ID = '"+ID+"'");
        //   ResultSet rs = db.ps.executeQuery("select *from studentdetails inner join subject where studentdetails.ID='"+ID+"' and subject.ID='"+ID+"'");
            if(rs.next())
            {
                setVisible(false);
           //     new StudentResultSemester1().setVisible(true);
            }

            else
            {
                JOptionPane.showMessageDialog(null, "Roll No Does not Exist in our data");
            }
        }
        catch(HeadlessException | SQLException e1)
        {
            JOptionPane.showMessageDialog(null, "Conncetion Fail");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSeeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSeeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSeeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSeeResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSeeResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextFieldIDResult;
    // End of variables declaration//GEN-END:variables

    private void updateTable() {
       try
        {    
        DatabaseConnection db = new DatabaseConnection();
        String sql = "select *from studentdetails";
        ResultSet rs = db.ps.executeQuery(sql);
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));  
        }
        
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Conncetion Fail");
        }
    }
}
